/**
 * Config Generator Service
 * Generates device configuration files
 */

import type { 
  DeviceConfig, 
  CloudflareTunnelConfig, 
  GeneratedFile, 
  ConfigPackage,
  TargetPlatform 
} from '../types';

export class ConfigGeneratorService {
  private outputDir: string;

  constructor(outputDir: string) {
    this.outputDir = outputDir;
  }

  generateDeviceId(): string {
    const randomPart = Math.random().toString(36).substring(2, 10);
    return `freemen-${randomPart}`;
  }

  generateDeviceConfig(
    deviceId: string,
    name: string,
    platform: TargetPlatform,
    _cloudflare: CloudflareTunnelConfig
  ): DeviceConfig {
    return {
      id: deviceId,
      name,
      platform,
      createdAt: new Date().toISOString(),
    };
  }

  generateEnvContent(
    deviceId: string,
    hostname: string,
    tunnelToken: string,
    port: number = 6500
  ): string {
    return `# Freemen Printer Proxy - Device Configuration
# Generated by Freemen Provisioner
# DO NOT COMMIT THIS FILE

# Device Identity
DEVICE_ID=${deviceId}

# Service Configuration
PORT=${port}
API_KEY=\${API_KEY:-change-me-in-production}

# Cloudflare Tunnel
TUNNEL_TOKEN=${tunnelToken}
PUBLIC_HOSTNAME=${hostname}

# Printer (configure after deployment)
PRINTER_IP=
PRINTER_PORT=9100
PRINTER_PROTOCOL=jetdirect
`;
  }

  generateDockerComposeOverride(tunnelToken: string): string {
    return `# Freemen Printer Proxy - Docker Compose Override
# Generated by Freemen Provisioner
# DO NOT COMMIT THIS FILE

version: '3.8'

services:
  freemen-printer-proxy:
    environment:
      - TUNNEL_TOKEN=${tunnelToken}

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: freemen-cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${tunnelToken}
    networks:
      - freemen-printer-proxy
    depends_on:
      - freemen-printer-proxy

networks:
  freemen-printer-proxy:
    external: true
`;
  }

  generateDeviceJson(
    device: DeviceConfig,
    cloudflare: CloudflareTunnelConfig,
    port: number = 6500
  ): string {
    return JSON.stringify({
      device,
      cloudflare: {
        accountId: cloudflare.accountId,
        zoneId: cloudflare.zoneId,
        zoneName: cloudflare.zoneName,
        tunnel: {
          id: cloudflare.tunnel.id,
          name: cloudflare.tunnel.name,
          hostname: cloudflare.hostname,
        },
      },
      service: {
        port,
        localUrl: `http://localhost:${port}`,
        publicUrl: `https://${cloudflare.hostname}`,
      },
    }, null, 2);
  }

  generateSetupScript(platform: TargetPlatform, deviceId: string, hostname: string): string {
    if (platform === 'raspberry-pi') {
      return this.generatePiSetupScript(deviceId, hostname);
    }
    return this.generateLinuxSetupScript(deviceId, hostname);
  }

  private generatePiSetupScript(deviceId: string, hostname: string): string {
    return `#!/bin/bash
# Freemen Printer Proxy - Raspberry Pi Setup
# Device: ${deviceId}

set -e

echo "Setting up Freemen Printer Proxy..."
echo "Device ID: ${deviceId}"
echo "Public URL: https://${hostname}"

# Check root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root (sudo ./setup.sh)"
  exit 1
fi

# Install Docker
if ! command -v docker &> /dev/null; then
  curl -fsSL https://get.docker.com | sh
  usermod -aG docker pi
fi

# Install cloudflared
if ! command -v cloudflared &> /dev/null; then
  curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-arm64 -o /usr/local/bin/cloudflared
  chmod +x /usr/local/bin/cloudflared
fi

# Setup complete
echo ""
echo "Setup complete!"
echo "Local:  http://localhost:6500"
echo "Public: https://${hostname}"
`;
  }

  private generateLinuxSetupScript(deviceId: string, hostname: string): string {
    return `#!/bin/bash
# Freemen Printer Proxy - Linux Setup
# Device: ${deviceId}

set -e

echo "Setting up Freemen Printer Proxy..."
echo "Device ID: ${deviceId}"
echo "Public URL: https://${hostname}"

# Check root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root (sudo ./setup.sh)"
  exit 1
fi

# Detect architecture
ARCH=$(uname -m)
case $ARCH in
  x86_64) CF_ARCH="amd64" ;;
  aarch64) CF_ARCH="arm64" ;;
  *) echo "Unsupported: $ARCH"; exit 1 ;;
esac

# Install Docker
if ! command -v docker &> /dev/null; then
  curl -fsSL https://get.docker.com | sh
fi

# Install cloudflared
if ! command -v cloudflared &> /dev/null; then
  curl -L "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-\${CF_ARCH}" -o /usr/local/bin/cloudflared
  chmod +x /usr/local/bin/cloudflared
fi

echo ""
echo "Setup complete!"
echo "Local:  http://localhost:6500"
echo "Public: https://${hostname}"
`;
  }

  generateReadme(device: DeviceConfig, cloudflare: CloudflareTunnelConfig, files: GeneratedFile[]): string {
    return `# Freemen Printer Proxy - Device Package

Generated by Freemen Provisioner

## Device Information

| Property | Value |
|----------|-------|
| Device ID | \`${device.id}\` |
| Device Name | ${device.name} |
| Platform | ${device.platform} |
| Public URL | https://${cloudflare.hostname} |

## Files

${files.map(f => `- **${f.name}** - ${f.description}`).join('\n')}

## Deployment

1. Copy this folder to your device
2. Run: \`sudo ./setup.sh\`
3. Configure your printer at http://localhost:6500

## Security

- DO NOT commit these files to version control
- Treat the tunnel token like a password
`;
  }

  async generatePackage(
    device: DeviceConfig,
    cloudflare: CloudflareTunnelConfig
  ): Promise<ConfigPackage> {
    const files: GeneratedFile[] = [];

    // device.json
    files.push({
      name: 'device.json',
      path: `${this.outputDir}/${device.id}/device.json`,
      description: 'Device configuration',
      content: this.generateDeviceJson(device, cloudflare),
    });

    // device.env
    files.push({
      name: 'device.env',
      path: `${this.outputDir}/${device.id}/device.env`,
      description: 'Environment variables',
      content: this.generateEnvContent(device.id, cloudflare.hostname, cloudflare.tunnel.token),
    });

    // docker-compose.cloudflare.yml
    files.push({
      name: 'docker-compose.cloudflare.yml',
      path: `${this.outputDir}/${device.id}/docker-compose.cloudflare.yml`,
      description: 'Docker Compose with cloudflared',
      content: this.generateDockerComposeOverride(cloudflare.tunnel.token),
    });

    // setup.sh
    files.push({
      name: 'setup.sh',
      path: `${this.outputDir}/${device.id}/setup.sh`,
      description: 'Setup script',
      content: this.generateSetupScript(device.platform, device.id, cloudflare.hostname),
    });

    // README.md
    files.push({
      name: 'README.md',
      path: `${this.outputDir}/${device.id}/README.md`,
      description: 'Instructions',
      content: this.generateReadme(device, cloudflare, files),
    });

    return {
      deviceId: device.id,
      outputDir: `${this.outputDir}/${device.id}`,
      files,
    };
  }
}

// Mock service for development
export class MockConfigGeneratorService extends ConfigGeneratorService {
  constructor() {
    super('./output');
  }

  async generatePackage(
    device: DeviceConfig,
    cloudflare: CloudflareTunnelConfig
  ): Promise<ConfigPackage> {
    // Simulate async operation
    await new Promise(resolve => setTimeout(resolve, 500));
    return super.generatePackage(device, cloudflare);
  }
}
