/**
 * Pi Setup - Flash SD Card Step
 *
 * Receives the already-downloaded image path and full Pi + tunnel config.
 * Flow: disk-select → confirm → preparing → flashing → writing-files → done
 *
 * After writing the OS image, this step:
 *  1. Restores the disk (lets Windows remount partitions)
 *  2. Detects the boot partition
 *  3. Hashes the password via the Tauri hash_password command
 *  4. Writes ssh, userconf.txt, wpa_supplicant.conf, custom.toml, firstrun.sh
 *  5. Patches cmdline.txt to auto-run firstrun.sh on first boot
 *
 * Browser fallback: manual checklist.
 */

import { useState, useEffect, useRef, useCallback } from 'react';
import { invoke } from '@tauri-apps/api/tauri';
import {
  HardDrive,
  CheckCircle,
  Circle,
  AlertTriangle,
  Loader2,
  RefreshCw,
  ChevronRight,
  Zap,
  X,
  Download,
  ExternalLink,
  FileText,
} from 'lucide-react';
import { Button } from '../../ui/Button';
import {
  isTauri,
  listPhysicalDisks,
  prepareDiskForFlash,
  flashImageToDisk,
  onFlashProgress,
  restoreDisk,
  cancelOperation,
  formatBytes,
  looksLikeSdCard,
  type PhysicalDisk,
  type FlashProgress,
} from '../../../services/os-flash-service';

// ============================================
// TYPES
// ============================================

export interface PiFlashConfig {
  hostname: string;
  username: string;
  password: string;
  wifiSsid: string;
  wifiPassword: string;
  wifiCountry: string;
  tunnelToken: string;
  printerPort: number;
  apiKey?: string;
}

interface PiFlashStepProps {
  imagePath: string | null;
  /** Pi system config + Cloudflare tunnel token. When provided, boot files are
   *  written automatically after flashing. */
  piConfig: PiFlashConfig | null;
  onNext: () => void;
  onBack: () => void;
}

// ============================================
// HELPERS — boot file generation
// ============================================

function buildUserconf(username: string, hashedPassword: string): string {
  return `${username}:${hashedPassword}`;
}

function buildWpaSupplicant(ssid: string, password: string, country: string): string {
  return `country=${country}
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1

network={
    ssid="${ssid}"
    psk="${password}"
    key_mgmt=WPA-PSK
}
`;
}

function buildCustomToml(cfg: PiFlashConfig): string {
  const wifi = cfg.wifiSsid
    ? `\n[wlan]\nssid = "${cfg.wifiSsid}"\npassword = "${cfg.wifiPassword}"\ncountry = "${cfg.wifiCountry}"\n`
    : '';
  return `# Raspberry Pi OS Configuration — generated by Freemen Provisioner

[system]
hostname = "${cfg.hostname}"

[user]
name = "${cfg.username}"

[ssh]
enabled = true
${wifi}`;
}

/**
 * firstrun.sh — runs via systemd.run at kernel-command-line.target (NO network yet).
 * Only does offline work: hostname, SSH, WiFi config, then installs the
 * freemen-install.service that runs AFTER network-online.target.
 */
function buildFirstRun(cfg: PiFlashConfig): string {
  return `#!/bin/bash
# Freemen first-boot stage 1 — offline setup only.
# Network-dependent installation happens in freemen-install.service on next boot.
set +e

BOOT_MOUNT="/boot/firmware"
[ -d "$BOOT_MOUNT" ] || BOOT_MOUNT="/boot"
BOOT_LOG="$BOOT_MOUNT/freemen-setup.log"

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$BOOT_LOG"; }
set_status() { echo "$1" > "$BOOT_MOUNT/freemen-status.txt" 2>/dev/null || true; log "STATUS: $1"; }

set_status "FIRSTRUN_STARTED"
log "=== firstrun.sh started (stage 1 — offline) ==="

# 1. Hostname
CURRENT_HOSTNAME=$(cat /etc/hostname | tr -d " \\t\\n\\r")
if raspi-config nonint do_hostname "${cfg.hostname}" 2>/dev/null; then
    log "Hostname set to ${cfg.hostname}"
else
    echo "${cfg.hostname}" > /etc/hostname
    sed -i "s/127.0.1.1.*$CURRENT_HOSTNAME/127.0.1.1\\t${cfg.hostname}/g" /etc/hosts
    log "Hostname set (fallback method)"
fi

# 2. SSH
systemctl enable ssh 2>/dev/null && log "SSH enabled" || log "WARNING: ssh enable failed"

# 3. Copy freemen-install.sh from boot partition to /usr/local/bin
if [ -f "$BOOT_MOUNT/freemen-install.sh" ]; then
    cp "$BOOT_MOUNT/freemen-install.sh" /usr/local/bin/freemen-install.sh
    chmod +x /usr/local/bin/freemen-install.sh
    log "freemen-install.sh copied to /usr/local/bin"
else
    set_status "ERROR_INSTALL_SCRIPT_MISSING"
    log "ERROR: freemen-install.sh not found on boot partition"
    exit 1
fi

# 4. Create systemd service to run installation after network is online
cat > /etc/systemd/system/freemen-install.service << 'SERVICE_EOF'
[Unit]
Description=Freemen Printer Proxy Installation
After=network-online.target
Wants=network-online.target
ConditionPathExists=/usr/local/bin/freemen-install.sh

[Service]
Type=oneshot
ExecStart=/usr/local/bin/freemen-install.sh
RemainAfterExit=yes
StandardOutput=journal+console
StandardError=journal+console

[Install]
WantedBy=multi-user.target
SERVICE_EOF

systemctl enable freemen-install.service && log "freemen-install.service enabled" || log "WARNING: service enable failed"

# 5. Clean up cmdline.txt so firstrun.sh doesn't run again
sed -i 's| systemd.run=[^ ]*firstrun.sh[^ ]*||g' "$BOOT_MOUNT/cmdline.txt" 2>/dev/null || true
rm -f "$BOOT_MOUNT/freemen-install.sh"

set_status "FIRSTRUN_COMPLETE_REBOOTING"
log "=== stage 1 complete — rebooting to run installation ==="
reboot
`;
}

/**
 * freemen-install.sh — written to boot partition, copied by firstrun.sh.
 * Runs as a systemd service AFTER network-online.target on second boot.
 * All network-dependent work (Docker, cloudflared, proxy) happens here.
 */
function buildInstallScript(cfg: PiFlashConfig): string {
  return `#!/bin/bash
# Freemen first-boot stage 2 — network installation.
# Runs as freemen-install.service after network-online.target.
set +e

BOOT_MOUNT="/boot/firmware"
[ -d "$BOOT_MOUNT" ] || BOOT_MOUNT="/boot"
BOOT_LOG="$BOOT_MOUNT/freemen-setup.log"
SYS_LOG="/var/log/freemen-setup.log"

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$SYS_LOG" "$BOOT_LOG"; }
set_status() { echo "$1" > "$BOOT_MOUNT/freemen-status.txt" 2>/dev/null || true; log "STATUS: $1"; }

set_status "INSTALL_STARTED"
log "=== freemen-install.sh started (stage 2 — network) ==="

# 1. Confirm network connectivity
set_status "CHECKING_NETWORK"
NETWORK_UP=0
for i in $(seq 1 30); do
    if ping -c 1 -W 3 1.1.1.1 >/dev/null 2>&1; then
        log "Network confirmed after \${i}x3s"
        NETWORK_UP=1
        break
    fi
    sleep 3
done
if [ "\$NETWORK_UP" -eq 0 ]; then
    set_status "ERROR_NO_NETWORK"
    log "ERROR: No network. Check ethernet cable or WiFi credentials."
    exit 1
fi

# 2. System updates
set_status "UPDATING_SYSTEM"
apt-get update -q && log "apt-get update done" || { set_status "ERROR_APT_UPDATE"; log "ERROR: apt-get update failed"; exit 1; }
apt-get install -y -q curl ca-certificates && log "packages installed" || { set_status "ERROR_APT_INSTALL"; log "ERROR: apt install failed"; exit 1; }

# 3. Docker
set_status "INSTALLING_DOCKER"
if ! command -v docker >/dev/null 2>&1; then
    log "Installing Docker..."
    curl -fsSL https://get.docker.com | sh && log "Docker installed" || { set_status "ERROR_DOCKER_INSTALL"; log "ERROR: Docker install failed"; exit 1; }
    usermod -aG docker "${cfg.username}"
    systemctl enable docker
    systemctl start docker
else
    log "Docker already present"
fi

# 4. cloudflared
set_status "INSTALLING_CLOUDFLARED"
if ! command -v cloudflared >/dev/null 2>&1; then
    log "Downloading cloudflared..."
    curl -fsSL -o /usr/local/bin/cloudflared \\
        https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-arm64 \\
        && chmod +x /usr/local/bin/cloudflared \\
        && log "cloudflared downloaded" \\
        || { set_status "ERROR_CLOUDFLARED_DOWNLOAD"; log "ERROR: cloudflared download failed"; exit 1; }
fi

set_status "CONFIGURING_TUNNEL"
cloudflared service install "${cfg.tunnelToken}" && log "Tunnel service installed" || { set_status "ERROR_TUNNEL_INSTALL"; log "ERROR: tunnel token rejected or cloudflared install failed"; exit 1; }
systemctl enable cloudflared
systemctl start cloudflared && log "cloudflared started" || log "WARNING: cloudflared start failed"

# 5. Freemen Printer Proxy
set_status "INSTALLING_PROXY"
mkdir -p /opt/freemen-printer-proxy
cat > /opt/freemen-printer-proxy/docker-compose.yml << 'COMPOSE_EOF'
version: '3'
services:
  printer-proxy:
    image: ghcr.io/potarius/freemen-printer-proxy:latest
    restart: unless-stopped
    ports:
      - "${cfg.printerPort}:6500"
    environment:
      - NODE_ENV=production
      - API_KEY=${cfg.apiKey || 'change-me'}
COMPOSE_EOF

cd /opt/freemen-printer-proxy
docker compose pull && log "Image pulled" || { set_status "ERROR_DOCKER_PULL"; log "ERROR: docker pull failed"; exit 1; }
docker compose up -d && log "Proxy container started" || { set_status "ERROR_DOCKER_UP"; log "ERROR: docker compose up failed"; exit 1; }

cat > /etc/systemd/system/freemen-printer-proxy.service << 'SVC_EOF'
[Unit]
Description=Freemen Printer Proxy
After=docker.service network-online.target
Requires=docker.service

[Service]
WorkingDirectory=/opt/freemen-printer-proxy
ExecStart=/usr/bin/docker compose up
ExecStop=/usr/bin/docker compose down
Restart=always

[Install]
WantedBy=multi-user.target
SVC_EOF
systemctl enable freemen-printer-proxy

# 6. Self-disable so this service doesn't run again
systemctl disable freemen-install.service 2>/dev/null || true
rm -f /usr/local/bin/freemen-install.sh /etc/systemd/system/freemen-install.service

set_status "COMPLETE"
log "=== Freemen installation complete ==="
`;
}

// ============================================
// WRITE BOOT FILES
// ============================================

async function writeBootFiles(
  bootLetter: string,
  cfg: PiFlashConfig,
  onStatus: (msg: string) => void,
): Promise<void> {
  const base = `${bootLetter}:`;

  onStatus('Hashing password…');
  const hashedPassword = await invoke<string>('hash_password', { password: cfg.password });

  onStatus('Writing ssh…');
  await invoke('write_file', { path: `${base}\\ssh`, content: '' });

  onStatus('Writing userconf.txt…');
  await invoke('write_file', {
    path: `${base}\\userconf.txt`,
    content: buildUserconf(cfg.username, hashedPassword),
  });

  if (cfg.wifiSsid && cfg.wifiPassword) {
    onStatus('Writing wpa_supplicant.conf…');
    await invoke('write_file', {
      path: `${base}\\wpa_supplicant.conf`,
      content: buildWpaSupplicant(cfg.wifiSsid, cfg.wifiPassword, cfg.wifiCountry),
    });
  }

  onStatus('Writing custom.toml…');
  await invoke('write_file', { path: `${base}\\custom.toml`, content: buildCustomToml(cfg) });

  onStatus('Writing firstrun.sh…');
  await invoke('write_file', { path: `${base}\\firstrun.sh`, content: buildFirstRun(cfg) });

  onStatus('Writing freemen-install.sh…');
  await invoke('write_file', { path: `${base}\\freemen-install.sh`, content: buildInstallScript(cfg) });

  // Patch cmdline.txt — append systemd.run directive so firstrun.sh auto-executes
  onStatus('Patching cmdline.txt…');
  try {
    const existing = await invoke<string>('read_file', { path: `${base}\\cmdline.txt` });
    const line = existing.trimEnd();
    if (!line.includes('firstrun.sh')) {
      // Raspberry Pi OS Bookworm mounts the boot partition at /boot/firmware.
      // Older releases (Bullseye) used /boot. We always write /boot/firmware
      // because the downloaded image is the current Bookworm release.
      const patched =
        line +
        ' systemd.run=/boot/firmware/firstrun.sh systemd.run_success_action=reboot systemd.unit=kernel-command-line.target\n';
      await invoke('write_file', { path: `${base}\\cmdline.txt`, content: patched });
    }
  } catch {
    // cmdline.txt patch is best-effort; if it fails the user can run firstrun.sh manually
    console.warn('Could not patch cmdline.txt — firstrun.sh will not auto-run on first boot');
  }
}

// Detect the boot partition drive letter by polling detect_drives
async function detectBootPartition(maxWaitMs = 30_000): Promise<string | null> {
  const deadline = Date.now() + maxWaitMs;
  while (Date.now() < deadline) {
    try {
      const drives = await invoke<Array<{
        letter: string;
        label: string;
        size: number;
        is_removable: boolean;
      }>>('detect_drives');

      const boot = drives.find(
        (d) =>
          d.label.toLowerCase().includes('boot') ||
          (d.is_removable && d.size > 0 && d.size < 800 * 1024 * 1024),
      );
      if (boot) return boot.letter;
    } catch {
      // ignore transient errors while disk remounts
    }
    await new Promise((r) => setTimeout(r, 3000));
  }
  return null;
}

// ============================================
// TOP-LEVEL BRANCH
// ============================================

export function PiFlashStep({ imagePath, piConfig, onNext, onBack }: PiFlashStepProps) {
  if (isTauri()) {
    return <FlashWizard imagePath={imagePath} piConfig={piConfig} onNext={onNext} onBack={onBack} />;
  }
  return <ManualChecklist onNext={onNext} onBack={onBack} />;
}

// ============================================
// FLASH WIZARD  (Tauri)
// ============================================

type Phase = 'disk-select' | 'confirm' | 'preparing' | 'flashing' | 'writing-files' | 'done' | 'error';

function FlashWizard({
  imagePath,
  piConfig,
  onNext,
  onBack,
}: {
  imagePath: string | null;
  piConfig: PiFlashConfig | null;
  onNext: () => void;
  onBack: () => void;
}) {
  const [phase, setPhase] = useState<Phase>('disk-select');
  const [disks, setDisks] = useState<PhysicalDisk[]>([]);
  const [selectedDisk, setSelectedDisk] = useState<PhysicalDisk | null>(null);
  const [isLoadingDisks, setIsLoadingDisks] = useState(false);
  const [diskError, setDiskError] = useState<string | null>(null);
  const [flashProgress, setFlashProgress] = useState<FlashProgress | null>(null);
  const [flashError, setFlashError] = useState<string | null>(null);
  const [fileStatus, setFileStatus] = useState('');

  const unlistenRef = useRef<(() => void) | null>(null);

  useEffect(() => {
    handleLoadDisks();
    return () => { unlistenRef.current?.(); };
  }, []);

  const handleLoadDisks = useCallback(async () => {
    setIsLoadingDisks(true);
    setDiskError(null);
    try {
      const found = await listPhysicalDisks();
      setDisks(found);
      setSelectedDisk(found.find(looksLikeSdCard) ?? null);
    } catch (err) {
      setDiskError(String(err));
    } finally {
      setIsLoadingDisks(false);
    }
  }, []);

  const handleStartFlash = useCallback(async () => {
    if (!selectedDisk || !imagePath) return;
    setFlashError(null);
    setPhase('preparing');

    try {
      const unlisten = await onFlashProgress((p) => setFlashProgress(p));
      unlistenRef.current = unlisten;

      await prepareDiskForFlash(selectedDisk.number);
      setPhase('flashing');

      await flashImageToDisk(imagePath, selectedDisk.number);
      unlisten();
      unlistenRef.current = null;

      // Restore disk so partitions remount
      await restoreDisk(selectedDisk.number).catch(console.warn);

      // If we have Pi config, write boot files
      if (piConfig) {
        setPhase('writing-files');
        setFileStatus('Waiting for boot partition…');

        const bootLetter = await detectBootPartition(45_000);
        if (!bootLetter) {
          throw new Error(
            'Boot partition did not appear after 45 seconds. Remove and reinsert the SD card, then try again.',
          );
        }

        await writeBootFiles(bootLetter, piConfig, setFileStatus);
      }

      setPhase('done');
      setTimeout(() => onNext(), 900);
    } catch (err) {
      unlistenRef.current?.();
      unlistenRef.current = null;

      const msg = String(err);
      if (msg === 'cancelled') {
        setPhase('disk-select');
        setFlashProgress(null);
      } else {
        setFlashError(msg);
        setPhase('error');
      }
      restoreDisk(selectedDisk.number).catch(console.warn);
    }
  }, [selectedDisk, imagePath, piConfig, onNext]);

  // ── RENDER ────────────────────────────────────────────────────────────────

  return (
    <div className="animate-fade-in max-w-2xl mx-auto">
      {/* Header */}
      <div className="text-center mb-8">
        <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-orange-500/20 to-red-500/20 flex items-center justify-center mx-auto mb-4">
          <HardDrive className="w-8 h-8 text-orange-400" />
        </div>
        <h2 className="text-2xl font-bold text-white mb-2">Flash SD Card</h2>
        <p className="text-surface-400">
          {piConfig
            ? 'Write OS image and all configuration to your SD card'
            : 'Write Raspberry Pi OS to your SD card'}
        </p>
      </div>

      {/* No image guard */}
      {!imagePath && (
        <div className="p-4 rounded-xl bg-yellow-500/10 border border-yellow-500/20 mb-6">
          <div className="flex gap-3">
            <AlertTriangle className="w-5 h-5 text-yellow-400 flex-shrink-0 mt-0.5" />
            <p className="text-sm text-surface-300">No OS image found. Go back and download it first.</p>
          </div>
        </div>
      )}

      {/* Disk select */}
      {phase === 'disk-select' && (
        <div className="space-y-6">
          <div className="p-4 rounded-xl bg-yellow-500/10 border border-yellow-500/20">
            <div className="flex gap-3">
              <AlertTriangle className="w-5 h-5 text-yellow-400 flex-shrink-0 mt-0.5" />
              <p className="text-sm text-yellow-300">
                <strong>All data on the selected disk will be erased.</strong> Make sure
                you pick the correct SD card — not your main drive.
              </p>
            </div>
          </div>

          {diskError && (
            <div className="p-4 rounded-xl bg-red-500/10 border border-red-500/20">
              <p className="text-sm text-red-300">{diskError}</p>
              <p className="text-xs text-surface-500 mt-1">Run as Administrator to list physical disks.</p>
            </div>
          )}

          <div className="flex items-center justify-between">
            <p className="text-sm font-medium text-surface-400">Select your SD card</p>
            <Button
              variant="ghost"
              size="sm"
              onClick={handleLoadDisks}
              disabled={isLoadingDisks}
              leftIcon={isLoadingDisks ? <Loader2 className="w-4 h-4 animate-spin" /> : <RefreshCw className="w-4 h-4" />}
            >
              Refresh
            </Button>
          </div>

          {!isLoadingDisks && disks.length === 0 && !diskError && (
            <div className="p-8 rounded-xl border-2 border-dashed border-surface-700 text-center">
              <HardDrive className="w-10 h-10 text-surface-600 mx-auto mb-3" />
              <p className="text-surface-400">No disks detected. Insert your SD card and refresh.</p>
            </div>
          )}

          <div className="space-y-2">
            {disks.map((disk) => {
              const recommended = looksLikeSdCard(disk);
              const isSelected = selectedDisk?.number === disk.number;
              return (
                <button
                  key={disk.number}
                  onClick={() => setSelectedDisk(disk)}
                  className={`w-full p-4 rounded-xl border text-left transition-all ${
                    isSelected
                      ? 'bg-freemen-500/10 border-freemen-500/50'
                      : 'bg-surface-900/50 border-surface-700 hover:bg-surface-800/50 hover:border-surface-600'
                  }`}
                >
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-3">
                      <div className={`w-10 h-10 rounded-lg flex items-center justify-center ${isSelected ? 'bg-freemen-500/20' : 'bg-surface-800'}`}>
                        <HardDrive className={`w-5 h-5 ${isSelected ? 'text-freemen-400' : 'text-surface-400'}`} />
                      </div>
                      <div>
                        <div className="flex items-center gap-2">
                          <span className={`font-medium ${isSelected ? 'text-freemen-400' : 'text-white'}`}>
                            {disk.friendlyName}
                          </span>
                          {recommended && (
                            <span className="px-2 py-0.5 text-xs rounded-full bg-green-500/20 text-green-400">
                              Recommended
                            </span>
                          )}
                        </div>
                        <p className="text-sm text-surface-500">
                          Disk {disk.number} · {formatBytes(disk.size)} · {disk.busType} · {disk.status}
                        </p>
                      </div>
                    </div>
                    <div className={`w-5 h-5 rounded-full border-2 flex items-center justify-center ${isSelected ? 'border-freemen-500 bg-freemen-500' : 'border-surface-600'}`}>
                      {isSelected && <CheckCircle className="w-3 h-3 text-white" />}
                    </div>
                  </div>
                </button>
              );
            })}
          </div>

          <div className="flex justify-between pt-2">
            <Button variant="ghost" onClick={onBack}>Back</Button>
            <Button
              onClick={() => setPhase('confirm')}
              disabled={!selectedDisk || !imagePath}
              rightIcon={<ChevronRight className="w-4 h-4" />}
            >
              Continue
            </Button>
          </div>
        </div>
      )}

      {/* Confirm */}
      {phase === 'confirm' && selectedDisk && (
        <div className="space-y-6">
          <div className="p-5 rounded-xl bg-orange-500/10 border border-orange-500/30">
            <div className="flex gap-3">
              <AlertTriangle className="w-6 h-6 text-orange-400 flex-shrink-0" />
              <div>
                <h4 className="font-semibold text-orange-400 mb-1">This will erase all data</h4>
                <p className="text-sm text-surface-300">
                  Everything on <strong className="text-white">{selectedDisk.friendlyName}</strong> (
                  {formatBytes(selectedDisk.size)}) will be permanently overwritten.
                </p>
              </div>
            </div>
          </div>

          <div className="p-4 rounded-xl bg-surface-900/50 border border-surface-700">
            <p className="text-xs text-surface-500 uppercase font-medium mb-3">What will happen</p>
            <div className="space-y-2 text-sm">
              <div className="flex items-center gap-2 text-surface-300">
                <CheckCircle className="w-4 h-4 text-green-400 flex-shrink-0" />
                Write OS image to {selectedDisk.friendlyName} ({formatBytes(selectedDisk.size)})
              </div>
              {piConfig && (
                <>
                  <div className="flex items-center gap-2 text-surface-300">
                    <CheckCircle className="w-4 h-4 text-green-400 flex-shrink-0" />
                    Configure hostname <code className="text-freemen-400">{piConfig.hostname}</code> and user <code className="text-freemen-400">{piConfig.username}</code>
                  </div>
                  {piConfig.wifiSsid && (
                    <div className="flex items-center gap-2 text-surface-300">
                      <CheckCircle className="w-4 h-4 text-green-400 flex-shrink-0" />
                      Configure WiFi: <code className="text-freemen-400">{piConfig.wifiSsid}</code>
                    </div>
                  )}
                  <div className="flex items-center gap-2 text-surface-300">
                    <CheckCircle className="w-4 h-4 text-green-400 flex-shrink-0" />
                    Write Cloudflare tunnel config + auto-start script
                  </div>
                </>
              )}
            </div>
          </div>

          <div className="flex justify-between">
            <Button variant="ghost" onClick={() => setPhase('disk-select')}>Back</Button>
            <Button
              onClick={handleStartFlash}
              className="bg-gradient-to-r from-orange-500 to-red-500 hover:from-orange-600 hover:to-red-600"
              leftIcon={<Zap className="w-4 h-4" />}
            >
              Flash Everything
            </Button>
          </div>
        </div>
      )}

      {/* Preparing */}
      {phase === 'preparing' && (
        <div className="space-y-6">
          <div className="text-center py-8">
            <Loader2 className="w-10 h-10 text-orange-400 animate-spin mx-auto mb-4" />
            <p className="text-white font-medium">Preparing disk…</p>
            <p className="text-sm text-surface-400 mt-1">Removing drive letter assignments</p>
          </div>
          <div className="p-4 rounded-xl bg-blue-500/10 border border-blue-500/20">
            <div className="flex gap-3">
              <AlertTriangle className="w-5 h-5 text-blue-400 flex-shrink-0 mt-0.5" />
              <p className="text-sm text-blue-200">
                If Windows asks <strong>"Do you want to format the disk?"</strong>, click <strong>Cancel</strong>. This is normal — the Linux partitions are not readable by Windows.
              </p>
            </div>
          </div>
        </div>
      )}

      {/* Flashing */}
      {phase === 'flashing' && (
        <div className="space-y-6">
          <div className="p-6 rounded-2xl bg-surface-900/50 border border-surface-800">
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center gap-3">
                <Loader2 className="w-5 h-5 text-orange-400 animate-spin" />
                <span className="font-medium text-white">Writing OS image…</span>
              </div>
              <span className="text-sm tabular-nums text-surface-400">
                {flashProgress ? `${flashProgress.percent.toFixed(1)}%` : '—'}
              </span>
            </div>
            <div className="h-2.5 bg-surface-800 rounded-full overflow-hidden mb-3">
              <div
                className="h-full bg-gradient-to-r from-orange-500 to-red-500 transition-all duration-300 rounded-full"
                style={{ width: `${flashProgress?.percent ?? 0}%` }}
              />
            </div>
            <div className="flex justify-between text-xs text-surface-500">
              <span>{flashProgress ? `Written: ${formatBytes(flashProgress.written)}` : 'Starting…'}</span>
              <span>~5–15 minutes</span>
            </div>
          </div>
          <div className="p-3 rounded-xl bg-yellow-500/10 border border-yellow-500/20 text-center">
            <p className="text-sm text-yellow-300">Do not remove the SD card</p>
          </div>
          <div className="p-3 rounded-xl bg-blue-500/10 border border-blue-500/20">
            <p className="text-sm text-blue-200">
              If Windows asks to format a disk, click <strong>Cancel</strong> — this is normal for Linux partitions.
            </p>
          </div>
          <div className="flex justify-center">
            <Button variant="ghost" onClick={cancelOperation} leftIcon={<X className="w-4 h-4" />}>
              Cancel
            </Button>
          </div>
        </div>
      )}

      {/* Writing files */}
      {phase === 'writing-files' && (
        <div className="space-y-6">
          <div className="p-6 rounded-2xl bg-surface-900/50 border border-surface-800">
            <div className="flex items-center gap-3 mb-4">
              <Loader2 className="w-5 h-5 text-blue-400 animate-spin" />
              <span className="font-medium text-white">Writing configuration files…</span>
            </div>
            <p className="text-sm text-surface-400">{fileStatus}</p>
          </div>
          {piConfig && (
            <div className="p-4 rounded-xl bg-surface-900/30 border border-surface-800 space-y-2 text-sm text-surface-400">
              <div className="flex items-center gap-2"><FileText className="w-4 h-4" /> ssh — enable SSH on first boot</div>
              <div className="flex items-center gap-2"><FileText className="w-4 h-4" /> userconf.txt — user <code className="text-freemen-400">{piConfig.username}</code></div>
              {piConfig.wifiSsid && <div className="flex items-center gap-2"><FileText className="w-4 h-4" /> wpa_supplicant.conf — WiFi: {piConfig.wifiSsid}</div>}
              <div className="flex items-center gap-2"><FileText className="w-4 h-4" /> custom.toml — hostname & config</div>
              <div className="flex items-center gap-2"><FileText className="w-4 h-4" /> firstrun.sh — stage 1: hostname, SSH, registers install service</div>
              <div className="flex items-center gap-2"><FileText className="w-4 h-4" /> freemen-install.sh — stage 2: Docker, cloudflared, printer proxy (runs after network)</div>
              <div className="flex items-center gap-2"><FileText className="w-4 h-4" /> cmdline.txt — auto-run firstrun.sh on boot</div>
            </div>
          )}
          <div className="p-3 rounded-xl bg-yellow-500/10 border border-yellow-500/20 text-center">
            <p className="text-sm text-yellow-300">Do not remove the SD card</p>
          </div>
        </div>
      )}

      {/* Done */}
      {phase === 'done' && (
        <div className="text-center py-12">
          <div className="w-20 h-20 rounded-full bg-green-500/20 flex items-center justify-center mx-auto mb-6">
            <CheckCircle className="w-10 h-10 text-green-400" />
          </div>
          <p className="text-white font-semibold text-xl mb-2">SD card is ready!</p>
          <p className="text-surface-400">
            OS flashed and all configuration written. Insert the card into your Pi and power it on.
          </p>
        </div>
      )}

      {/* Error */}
      {phase === 'error' && (
        <div className="space-y-6">
          <div className="p-4 rounded-xl bg-red-500/10 border border-red-500/20">
            <div className="flex gap-3">
              <AlertTriangle className="w-5 h-5 text-red-400 flex-shrink-0 mt-0.5" />
              <div>
                <p className="font-medium text-red-400 mb-1">Operation failed</p>
                <p className="text-sm text-surface-300">{flashError}</p>
                {flashError?.includes('Administrator') && (
                  <p className="text-xs text-surface-500 mt-2">
                    Right-click the app → "Run as Administrator", then try again.
                  </p>
                )}
              </div>
            </div>
          </div>
          <div className="flex justify-between">
            <Button variant="ghost" onClick={() => setPhase('disk-select')}>Back</Button>
            <Button onClick={() => { setPhase('disk-select'); setFlashProgress(null); setFlashError(null); }}>
              Try Again
            </Button>
          </div>
        </div>
      )}
    </div>
  );
}

// ============================================
// MANUAL CHECKLIST  (browser fallback)
// ============================================

function ManualChecklist({ onNext, onBack }: { onNext: () => void; onBack: () => void }) {
  const [checklist, setChecklist] = useState({
    downloaded: false,
    opened: false,
    selected: false,
    flashed: false,
    ejected: false,
  });

  const allChecked = Object.values(checklist).every(Boolean);
  const toggle = (key: keyof typeof checklist) =>
    setChecklist((p) => ({ ...p, [key]: !p[key] }));

  return (
    <div className="animate-fade-in max-w-3xl mx-auto">
      <div className="text-center mb-10">
        <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-blue-500/20 to-cyan-500/20 flex items-center justify-center mx-auto mb-4">
          <HardDrive className="w-8 h-8 text-blue-400" />
        </div>
        <h2 className="text-2xl font-bold text-white mb-2">Flash SD Card</h2>
        <p className="text-surface-400">
          Use Raspberry Pi Imager to flash Pi OS Lite (64-bit) to your SD card
        </p>
      </div>

      <div className="p-4 rounded-xl bg-yellow-500/10 border border-yellow-500/20 mb-8">
        <div className="flex gap-3">
          <AlertTriangle className="w-5 h-5 text-yellow-400 flex-shrink-0 mt-0.5" />
          <p className="text-sm text-surface-300">
            Use <strong>Raspberry Pi OS Lite (64-bit)</strong> — not the Desktop version.
          </p>
        </div>
      </div>

      <div className="p-6 rounded-2xl bg-surface-900/50 border border-surface-800 mb-6">
        <div className="flex items-start justify-between gap-4">
          <div>
            <h3 className="font-semibold text-white mb-1">Raspberry Pi Imager</h3>
            <p className="text-sm text-surface-400">Official flashing tool</p>
          </div>
          <a href="https://www.raspberrypi.com/software/" target="_blank" rel="noopener noreferrer">
            <Button variant="secondary" leftIcon={<Download className="w-4 h-4" />}>
              Download
              <ExternalLink className="w-3 h-3 ml-1 opacity-50" />
            </Button>
          </a>
        </div>
      </div>

      <div className="p-6 rounded-2xl bg-surface-900/50 border border-surface-800 mb-8">
        <h3 className="font-semibold text-white mb-4">Checklist</h3>
        <div className="space-y-3">
          {([
            ['downloaded', 'Downloaded Raspberry Pi Imager', 'Installed on this computer'],
            ['opened', 'Opened Raspberry Pi Imager', 'Application is running'],
            ['selected', 'Selected Raspberry Pi OS Lite (64-bit)', 'Under "Raspberry Pi OS (other)"'],
            ['flashed', 'Flashed to SD card', 'Wait for write and verification to complete'],
            ['ejected', 'Safely ejected SD card', 'Then re-insert it to access the boot partition'],
          ] as [keyof typeof checklist, string, string][]).map(([key, title, desc]) => (
            <button
              key={key}
              onClick={() => toggle(key)}
              className={`w-full flex items-start gap-3 p-3 rounded-lg text-left transition-colors ${
                checklist[key]
                  ? 'bg-green-500/10 border border-green-500/30'
                  : 'bg-surface-900/50 border border-surface-800 hover:bg-surface-800/50'
              }`}
            >
              <div className="mt-0.5">
                {checklist[key] ? <CheckCircle className="w-5 h-5 text-green-400" /> : <Circle className="w-5 h-5 text-surface-500" />}
              </div>
              <div>
                <p className={`font-medium ${checklist[key] ? 'text-green-400' : 'text-white'}`}>{title}</p>
                <p className="text-sm text-surface-400">{desc}</p>
              </div>
            </button>
          ))}
        </div>
      </div>

      <div className="flex justify-between">
        <Button variant="ghost" onClick={onBack}>Back</Button>
        <Button onClick={onNext} disabled={!allChecked}>
          {allChecked ? 'Continue' : 'Complete checklist to continue'}
        </Button>
      </div>
    </div>
  );
}
